stages:
  - test

default:
  image: greycastle/flutter:1.22.3

cache:
  paths:
    - /flutter/bin/cache/dart-sdk

build:
  stage: test
  script:
    - apt-get update && apt-get install -y xdg-user-dirs
    - echo $API_KEY > assets/data/apiConfiguration.json
    - flutter analyze
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
    - rm assets/data/apiConfiguration.json
    - mv coverage/ public/
  artifacts:
    paths:
      - public