stages:
  - test
  - build
  - deploy

unit_test:
  image: brianegan/flutter_lcov:v0.5.1
  stage: test
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - coverage/

build:
  image: brianegan/flutter_lcov:v0.5.1
  stage: build
  script:
    - flutter build apk --release
    artifacts:
      paths:
        - build/app/outputs/apk/app.apk

pages:
  image: alpine
  stage: deploy
  dependencies:
    - unit_test
  script:
    - mkdir public
    - mv coverage/ public/coverage/
    - mv build/app/outputs/apk/app.apk public/app.apk
  artifacts:
    paths:
      - public
  only:
    - master