stages:
  - test
  - deploy

cache:
  paths:
    - /flutter/bin/cache/dart-sdk

unit_test:
  except:
    - master
  image: flutter_lcov_docker
  stage: test
  script:
    - flutter channel master
    - flutter upgrade
    - echo $API_KEY > assets/data/apiConfiguration.json
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
    - rm assets/data/apiConfiguration.json
  artifacts:
    paths:
      - coverage/

pages:
  image: alpine
  except:
    - master
  stage: deploy
  dependencies:
    - unit_test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
