stages:
  - test

cache:
  paths:
    - /flutter/bin/cache/dart-sdk

pages:
  image: cirrusci/flutter
  stage: test
  script:
    - flutter channel master
    - flutter upgrade
    - echo $API_KEY > assets/data/apiConfiguration.json
    - flutter analyze
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
    - rm assets/data/apiConfiguration.json
    - mv coverage/ public/
  artifacts:
    paths:
      - public