name: travelconverter
description: Handy multi-currency converter specifically for backpackers.
version: 2.0.0+94

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.35.7"

dependencies:

  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter
  intl:

  # navigation
  go_router: ^14.2.0

  # state
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2

  # utilities
  json_annotation: 4.9.0
  path_provider: ^2.1.3
  http: ^1.2.1
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.1.2
  device_preview:

  # user interface
  app_review_plus: ^2.3.3
  animated_snack_bar: ^0.4.0
  flutter_markdown: ^0.7.4
  url_launcher: ^6.3.0
  flutter_animate: ^4.5.2
  rive: ^0.13.9
  expressions: ^0.2.5

  # analytics and crashes
  firebase_core: 3.8.0
  firebase_analytics: ^11.3.5

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
  build_runner: ^2.4.13
  json_serializable: ^6.9.3

  # generating icons and splash
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon_adaptive.png

flutter_launcher_icons:
  android: icon
  ios: AppIcon
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/app_icon_adaptive.png
  remove_alpha_ios: true
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/data/currencies.json
    - assets/data/rates.json
    - assets/data/countries.json

    # Contains the secret api keys, needs to be manually added on each client.
    # I wish this could be managed in a better way but Flutter currently does not allow
    # for using build time environment variables so this is the currently recommended approach.
    - assets/data/apiConfiguration.json

    # Android studio will warn that these doesn't exist but they do and it works just fine
    - assets/images/flags/
    - assets/images/flags/2x/

    # animations
    - assets/animations/