name: travelconverter
description: Handy multi-currency converter specifically for backpackers.
version: 1.5.7+85

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # navigation
  go_router: ^14.2.0

  # utilities
  json_annotation: 4.9.0
  path_provider: ^2.1.3
  http: ^1.2.1
  device_info_plus: ^10.1.0
  connectivity: ^3.0.6
  intl:

  # user interface
  app_review_plus: ^2.3.1
  animated_snack_bar: ^0.4.0

  # analytics and crashes
  firebase_core: 3.1.0
  firebase_analytics: ^11.0.1
  rive: ^0.13.8

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_generator: 0.4.1
  mockito: 5.4.4
  build_runner: 2.4.11
  json_serializable: 6.8.0

  # generating icons and splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon_adaptive.png

flutter_launcher_icons:
  android: icon
  ios: AppIcon
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/app_icon_adaptive.png
  remove_alpha_ios: true
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/data/currencies.json
    - assets/data/rates.json
    - assets/data/countries.json

    # Contains the secret api keys, needs to be manually added on each client.
    # I wish this could be managed in a better way but Flutter currently does not allow
    # for using build time environment variables so this is the currently recommended approach.
    - assets/data/apiConfiguration.json

    # Android studio will warn that these doesn't exist but they do and it works just fine
    - assets/images/flags/
    - assets/images/flags/2x/

    # animations
    - assets/animations/