name: travelconverter
description: Handy multi-currency converter specifically for backpackers.
version: 1.5.3+81

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_annotation:
  path_provider: ^2.0.11
  http: ^0.13.5
  device_info:
  connectivity: ^3.0.6
  app_review: ^2.1.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

  cupertino_icons:

  # analytics and crashes
  firebase_core: 2.3.0
  firebase_analytics: ^10.0.6


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_generator:
  mockito:
  build_runner:
  json_serializable:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/currencies.json
    - assets/data/rates.json
    - assets/data/countries.json

    # Contains the secret api keys, needs to be manually added on each client.
    # I wish this could be managed in a better way but Flutter currently does not allow
    # for using build time environment variables so this is the currently recommended approach.
    - assets/data/apiConfiguration.json

    # Android studio will warn that these doesn't exist but they do and it works just fine
    - assets/images/flags/
    - assets/images/flags/2x/

  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf