name: backpacking_currency_converter
description: Handy multi-currency converter specifically for backpackers.

dependencies:
  intl: ^0.15.6
  path_provider: ^0.4.1
  geolocation: ^0.2.1
  geocoder: ^0.0.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/currencies.json
    - assets/data/rates.json
    - assets/data/countries.json

    - assets/images/flag.png
    - assets/images/2.0x/flag.png

  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf