name: travelconverter
description: Handy multi-currency converter specifically for backpackers.
version: 1.6.0

dependencies:
  json_annotation: ^2.4.0
  path_provider: 0.5.0
  http: ^0.12.0+2
  device_info: ^0.4.0+2
  connectivity: ^0.3.1
  app_review: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  test: 1.6.2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_translation:
  mockito: ^4.1.0
  build_runner: ^1.0.0
  json_serializable: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/currencies.json
    - assets/data/rates.json
    - assets/data/countries.json

    # Contains the secret api keys, needs to be manually added on each client.
    # I wish this could be managed in a better way but Flutter currently does not allow
    # for using build time environment variables so this is the currently recommended approach.
    - assets/data/apiConfiguration.json

    # Android studio will warn that these doesn't exist but they do and it works just fine
    - assets/images/flags/
    - assets/images/flags/2x/

  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf