default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      export_method: "app-store",
      codesigning_identity: ENV["FASTLANE_CODE_SIGNING_IDENTITY"],
      export_options: {
        'signingStyle' => 'manual',
        provisioningProfiles: {
          "se.greycastle.travelconverter" => ENV["FASTLANE_PROVISIONING_PROFILE"],
        }
      }
    )
    upload_to_testflight(
      api_key_path: ENV['FASTLANE_API_KEY_PATH'],
      skip_waiting_for_build_processing: true
    )
  end
end
