name: Distribute application

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout credentials
        uses: actions/checkout@v3
        with:
          token: ${{secrets.CREDENTIALS_REPO_PAT}}
          repository: ${{secrets.CREDENTIALS_REPO_URL}}
          path: 'credentials'

      - name: Install the Apple certificate and provisioning profile
        run: build-scripts/install-apple-certificates.sh

      # To ensure we can get the flutter versions, fixing a version unknown issue
      # https://github.com/subosito/flutter-action/issues/188
      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'

      - name: Write API keys
        env:
          API_KEY_JSON: ${{secrets.API_KEY_JSON}}
        run: echo $API_KEY_JSON > assets/data/apiConfiguration.json

      - name: Distribute iOS version
        env:
          FASTLANE_APPLE_ID: ${{secrets.FASTLANE_APPLE_ID}}
          FASTLANE_ITC_TEAM_ID: ${{secrets.FASTLANE_ITC_TEAM_ID}}
          FASTLANE_PROVISIONING_PROFILE: ${{secrets.FASTLANE_PROVISIONING_PROFILE}}
          FASTLANE_TEAM_ID: ${{secrets.FASTLANE_TEAM_ID}}
          FASTLANE_USER: ${{secrets.FASTLANE_USER}}
          APPSTORE_CONNECT_API_KEY: ${{secrets.APPSTORE_CONNECT_API_KEY}}
          FASTLANE_CODE_SIGNING_IDENTITY: ${{secrets.FASTLANE_CODE_SIGNING_IDENTITY}}
        run: |
          # we have to do build outside of fastlane, otherwise cocopods won't work
          flutter packages get
          flutter clean
          flutter build ios --release --no-codesign
          echo "Flutter build successful."
          echo "Exporting API key"
          export FASTLANE_API_KEY_PATH=$RUNNER_TEMP/key.json
          echo -n "$APPSTORE_CONNECT_API_KEY" | base64 --decode --output $FASTLANE_API_KEY_PATH
          cd ios
          echo "Running fastlane"
          bundle exec fastlane ios beta --verbose
