name: Flutter lint and test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # To ensure we can get the flutter versions, fixing a version unknown issue
      # https://github.com/subosito/flutter-action/issues/188
      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          sudo apt update -y
          sudo apt install lcov -y

      - name: Write API keys
        run: echo $API_KEYS_JSON > assets/data/apiConfiguration.json

      - name: Run linting
        run: flutter analyze

      - name: Run tests
        run: |
          flutter pub global activate junitreport
          flutter test --coverage --machine | tojunit > testreport.xml
          genhtml coverage/lcov.info --output=coverage
      - name: Publish coverage report
        uses: nohmad/lcov-report-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-path: coverage/lcov.info